version: '3.4'

services:
  api:
    image: treeloc/api
    ports:
      - "4545:80"
    environment:
      MONGO_URL: "mongodb://mongodb:27017"
      MONGO_DATABASE_NAME: "TreeLoc"
    build:
      context: .
      dockerfile: src/TreeLoc.Api/Dockerfile

  loader:
    image: treeloc/loader
    ports:
      - "4546:80"
    environment:
      MONGO_URL: "mongodb://mongodb:27017"
      MONGO_DATABASE_NAME: "TreeLoc"
      LOADER_DELAY: "20"
    build:
      context: .
      dockerfile: src/TreeLoc.Loader/Dockerfile

  mongodb:
    image: mongo:latest
    environment:
      MONGO_DATA_DIR: "/data/db"
      MONGO_LOG_DIR: "/dev/null"
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodata: