name: CI

on:
  push:
    branches: [ master ]

jobs:
  buildAndPushApi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets. DOCKER_HUB_PASSWORD }}
          repository: treeloc/backend-api
          dockerfile: src/TreeLoc.Api/Dockerfile
          tags: latest
          tag_with_sha: true

  buildAndPushLoader:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets. DOCKER_HUB_PASSWORD }}
          repository: treeloc/backend-loader
          dockerfile: src/TreeLoc.Loader/Dockerfile
          tags: latest
          tag_with_sha: true
